import { NextResponse } from "next/server";
import { prisma } from "../../../lib/prisma";

export const dynamic = "force-dynamic";

export async function GET(req: Request) {
  try {
    const { searchParams } = new URL(req.url);
    const userId = searchParams.get("userId");

    if (!userId) {
      return NextResponse.json({ ok: false, error: "userId required" }, { status: 400 });
    }

    // Get saved meals from MealList where user has saved items
    const lists = await prisma.mealList.findMany({
      where: {
        userId,
        isAutoGenerated: false,
        name: "Saved",
      },
      include: {
        items: {
          include: {
            meal: {
              include: {
                user: {
                  select: {
                    id: true,
                    name: true,
                    username: true,
                    image: true,
                  },
                },
                _count: {
                  select: { likes: true, comments: true },
                },
              },
            },
          },
          orderBy: {
            createdAt: "desc",
          },
        },
      },
    });

    const savedMeals = lists.flatMap((list) =>
      list.items.map((item) => item.meal)
    );

    return NextResponse.json({ ok: true, data: savedMeals });
  } catch (error: any) {
    console.error("Error fetching saved meals:", error);
    return NextResponse.json(
      { ok: false, error: error?.message || "Failed to fetch saved meals" },
      { status: 500 }
    );
  }
}

export async function POST(req: Request) {
  try {
    const body = await req.json();
    const { userId, mealId } = body;

    if (!userId || !mealId) {
      return NextResponse.json(
        { ok: false, error: "userId and mealId required" },
        { status: 400 }
      );
    }

    // Find or create "Saved" list
    let savedList = await prisma.mealList.findFirst({
      where: {
        userId,
        name: "Saved",
        isAutoGenerated: false,
      },
    });

    if (!savedList) {
      savedList = await prisma.mealList.create({
        data: {
          userId,
          name: "Saved",
          isAutoGenerated: false,
          listType: "saved",
        },
      });
    }

    // Add meal to list
    await prisma.mealListItem.create({
      data: {
        listId: savedList.id,
        mealId,
      },
    });

    return NextResponse.json({ ok: true }, { status: 201 });
  } catch (error: any) {
    if (error.code === 'P2002') {
      // Already saved
      return NextResponse.json({ ok: true, data: { alreadySaved: true } });
    }
    console.error("Error saving meal:", error);
    return NextResponse.json(
      { ok: false, error: error?.message || "Failed to save meal" },
      { status: 500 }
    );
  }
}

export async function DELETE(req: Request) {
  try {
    const { searchParams } = new URL(req.url);
    const userId = searchParams.get("userId");
    const mealId = searchParams.get("mealId");

    if (!userId || !mealId) {
      return NextResponse.json(
        { ok: false, error: "userId and mealId required" },
        { status: 400 }
      );
    }

    const savedList = await prisma.mealList.findFirst({
      where: {
        userId,
        name: "Saved",
      },
    });

    if (savedList) {
      await prisma.mealListItem.deleteMany({
        where: {
          listId: savedList.id,
          mealId,
        },
      });
    }

    return NextResponse.json({ ok: true });
  } catch (error: any) {
    console.error("Error unsaving meal:", error);
    return NextResponse.json(
      { ok: false, error: error?.message || "Failed to unsave meal" },
      { status: 500 }
    );
  }
}

